### ISSUE TITLE
messages fail to deliver in v2.1

### ISSUE THREAD

**Issue by hedgepigdaniel** [TopCloud/socketcluster#55]
I just upgraded to sc2.1.4 and noticed that for some reason messages published in channels don't get delivered to subscribed clients anymore. The problem is not present in 2.0.28 and is present in 2.1.0.
```
1428570453888 - Origin: Worker (PID 26338)
    [Notice] Failed to deliver message 'a42d83e2-1061-4143-8fe9-d9372758fe6a' to 1 subscriber on the '["chat","onlinelist","courses/chocolate/Cohorts/ClassOf2014"]' channel
```

**Comment by jondubois** [comment]
@hedgepigdaniel I can't reproduce, Does it do this for every client? If so, you should try to remove the whole sc2/ directory then:

```js
npm cache clean
```

then do a fresh install:

```js
npm install sc2
```

I made some changes to dependencies but npm may be using the old dependencies from cache instead of getting the latest one when you updated sc2.

Note that in production, it would be normal to get a few of these notices occasionally if a client has a really bad connection (or one which isn't closed properly) - The ping timeout (60 seconds by default) will kill the socket if that's the case, but in the meantime, the socket could miss some messages.

In 2.1.4, SC will by default retry to deliver the failed messages to clients who didn't receive it due to a poor connection - This is to achieve 'guaranteed' exactly-once quality of service.

Having 'exactly once guarantee' by default is a bit extreme for most scenarios so in the next version, I'm going to revert the default back to 'at most once' (this is what it was before), you will be able to specify which Quality of Service level in the publish(channel, data, QoS) method. There will be three levels:
0 - 'at most once'
1 - 'exactly once guaranteed'
2 - 'exactly once, in-order guaranteed'

**Comment by hedgepigdaniel** [comment]
Cleaning the cache didn't fix it, but I can't reproduce the issue anymore. I'll get back to you if I can. Might have been some networking problem on my end.

Great to hear about the new QoS levels :)

**Comment by jondubois** [comment]
@hedgepigdaniel Strange. Note that some proxies could block WebSocket traffic when used over plain HTTP. Using it over HTTPS/WSS should fix the issue.

**Comment by jondubois** [comment]
@hedgepigdaniel Actually, I ended up changing the QoS levels idea. Instead there are just two levels: 'at most once' (default) and 'exactly-once-in-order'. I felt that level 1 was redundant when it ended up providing no performance advantage.

So for 'at most once':

```js
// callback is optional
socket.publish('channel', data, callback);
```

For 'exactly once in order':

```js
// boolean and callback are optional
socket.publish('channel', data, true, callback);
```

If you intentionally block messages using middleware functions, they will be counted as delivered. If you forget to call next() in your middleware, it will retry until it times out (2 minutes). There is an exponential backoff happening so it doesn't kill the server if lots of deliveries fail.
