### ISSUE TITLE
sc2 - List of Channels subscribed by a socket

### ISSUE THREAD

**Issue by mailmevenkat** [TopCloud/socketcluster#59]
Is it possible to get list of channels subscribed by a socket (backend)? or i got to implement custom store like redis for maintaining the rooms subscribed by a socket?

P.S: I need to ping other users when a socket leaves a channel unintentionally (like disconnect, browser crash, etc).

**Comment by jondubois** [comment]
Not right now - You have to keep track of it manually. But you don't need to use Redis, since each server-side server socket is only available in the current worker process. You could add your own activeSubscriptions property to the socket object on the server to keep track (for now).

A subscriptions([includePending]) method on the server-side SCSocket might make sense (right now it's only supported on the client). I'm considering adding all the pub/sub methods from the client-side of the socket onto the server-side of socket so that they'll be available on both sides.

Also, I plan to add a way to make it easier to track when sockets join or leave a channel on the server.

**Comment by jondubois** [comment]
@mailmevenkat I have added a socket.subscriptions() and a socket.isSubscribed(channelName) method to the server-side SCSocket object: http://socketcluster.io/#!/docs/api-scsocket-server

The change was done in iocluster (a dependency of SC) so you will need to 'npm cache clean' before you reinstall SC - Or you can navigate to your sc2 or socketcluster's node_modules/ directory and manually upgrade the iocluster module to the latest version.

**Comment by mailmevenkat** [comment]
The above first solution worked like a charm! I will try with the new one!

**Comment by mailmevenkat** [comment]
![screenshot from 2015-04-23 23 49 35](https://cloud.githubusercontent.com/assets/9083583/7304282/023b76ee-ea14-11e4-8cc6-93ea4b098573.png)

I manually checked iocluster/index.js , it has both Global.prototype.subscriptions and Global.prototype.isSubscribed , i don't think there is any problem in the file.

**Comment by jondubois** [comment]
Can't reproduce. Can you check the version of ioCluster in its package.json file? It should be 2.2.9.
When you're in your project directory try:

``bash
npm remove sc2
npm cache clean
npm install sc2
```

**Comment by jondubois** [comment]
@mailmevenkat Ok, now you can do:

```js
// Server code
socket.on('subscribe', subscribeHandler);
socket.on('unsubscribe', unsubscribeHandler);
```

The handlers in both cases receive a channelName string as argument.

Note that unsubscribe will trigger whenever a socket becomes unsubscribed from a channel (this includes unsubscribe triggered by disconnect so you don't have to handle the disconnect event separately for the purpose of checking which subscriptions were lost).

I will update the docs on website soon.

Also, I decided NOT to implement all of the pub/sub methods from the client SCSocket onto the server SCSocket - The reason is that you don't want the client and server side of the socket to fight over when to subscribe/unsubscribe/publish, etc... It could be a maintainability nightmare, especially when you consider with latency between them.

The control has to be given either to the server or to the client (but not both). The client is a much better place for this control in my opinion (it's more readable and explicit). The server's job is to decide whether or not to allow or block various client actions using middleware - The client is still in charge of how the data that flows in and out of the browser (this better for development) - The server effectively just manages permissions.

**Comment by jondubois** [comment]
This will be backported to SC1 soon but right now these changes only affect SC2.

**Comment by mailmevenkat** [comment]
Cool! This is way better for handling subscription! As of now i am using middleware for subcribe and custom channel list (as you suggested before) to handle disconnect. Will test this too. And ofcourse i have been using sc2.

**Comment by kjr247** [comment]
Is there a way to change this question? Since we've invalidated it with a different answer?
