### ISSUE TITLE
"parser error" when attempting to connect

### ISSUE THREAD

**Issue by woubuc** [TopCloud/socketcluster#61]
I'm developing a server for a multiplayer game, and decided to implement SocketCluster instead of socket.io which I previously used, since it does exactly what I need in terms of scaling. I have v2 set up and the server starts up and runs, using 6 workers, a balancer and a store process. My code is basically the example code (in coffeescript):

    # Server (app.js)
    cluster = new SocketCluster
    	appName: 'planets'
    	port: 8000
    	balancers: 1
    	stores: 1
    	workers: 6
    	workerController: './server.js'
    	transports: ['websocket']
    	logLevel: 3

    # Worker (server.js)
    app = do express
    httpServer = do worker.getHTTPServer
    socketServer = do worker.getSCServer
    
    httpServer.on 'request', app
    
    socketServer.on 'connection', (socket) ->
    	console.log 'Someone wants to say hi!'

And on the client, from the socketcluster-client example code:

    var options = {
    	host: '127.0.0.1',
    	port: 8000,
    	transports: ['websocket']
    }
    var socket = socketCluster.connect(options);
    socket.on('connect', function() {
    	console.log('Connected!');
    });

The client runs inside a nw.js window so I know it supports websockets, which is why I disabled polling. When I open it, it starts connecting to the server (I see the 'someone wants to say hi' log appear on the server), but then I get back a 'server error'. Closer inspection showed it was a 'parser error', but beyond that I couldn't really find what the problem was.

Am I just doing something wrong or is this a bug?

**Comment by jondubois** [comment]
@woubuc What is your version of SC2 client and server?
Note that you cannot use the SC2 server with the SC1 client (socketcluster-client). You need to make sure that the client inside node_modules/ is sc2-client.

Some notes:
- SC2 is always WebSocket - So you don't need to specify the transports option at all.
- SC2 doesn't use LoadBalancers - The workers take turns to pickup connections directly from the port (this is possible thanks to the pure WebSocket approach) - So you don't need to specify the 'balancers' option.

You should probably specify the workerController path like this:

```js
workerController: __dirname + '/server.js'
```

Otherwise, if you run your instance from a different directory, the path will be incorrect. Using __dirname ensures that it is relative to the current file's directory.

I don't think any of these things explain the issue you're getting though. Is this parser error being shown on the client or server? Is there any stack trace?

**Comment by jondubois** [comment]
@woubuc The other thing is that I haven't tested the server with CoffeeScript before, but I don't see why that would be a problem. Does the sample app work for you as is?

**Comment by woubuc** [comment]
@jondubois I've looked for a sc2-specific client code but there's no sc2-client repo that I can find and the NPM entry for sc2-client contains only socketcluster-client, which is the code I used. I already suspected I might have the wrong client (it kept trying to connect through polling and threw errors when that didn't work - which I then fixed by setting it to websocket only), but I couldn't find the correct js file for sc2, not even a reference to where it might be, so I figured the one client there was would work with both.

But anyhow, I'm guessing that's probably the cause of my problem then. Where can I find the sc2-client js?

The remarks you made about sc1 vs sc2 are things I had removed prior to running, since the docs stated they were unnecessary for sc2, but then it kept throwing errors so I added them back to see if it changed anything. It didn't help, but I haven't removed them again yet. I am going to set it right as soon as I get the whole thing working :)

The coffeescript is just my source code, it gets compiled to a javascript file which I then run, so the use of coffeescript couldn't really cause any errors.

**Comment by jondubois** [comment]
@woubuc The sc2-client is here: https://www.npmjs.com/package/sc2-client
When you run

You shouldn't have to think about it though if you run:

```js
npm install -g sc2
sc2 create myproject
```

^ The 'sc2 create' command automatically bundles sc2/ and sc2-client/ inside your node_module/ directory so you don't have to install them separately.

I'm thinking of making SC2 the official version of SC because the vast majority of people seem to be using it instead of SC1. There has been issues with other people mixing up the clients/server versions, so this is definitely a big problem.

**Comment by woubuc** [comment]
@jondubois I installed it like that in an empty directory and copied the correct js file to my client, since I don't need all the other stuff. It now works perfectly :smiley: 

For libraries I need in my client I usually just go to the github repo and download the js file from there, since that's all I really need. But there was no sc2-client repo that I could find so that's what confused me. I just needed that one js file to include in the client nwjs project, not the rest of the default setup, since I'm implementing socketcluster in existing code both server and client side (which used to use socket.io so a lot of the code is similar). So for my server I didn't install the default project either, I just installed the sc2 module and got what I needed for implementation from the docs. So perhaps you could offer the sc2 client files separately as well, instead of having to install it like that?

If most people already use sc2, it does sound like it may be time to make that the major version. But, do keep the original one alive as well, don't just pull the plug on it, in case people need a library that can fallback to polling (for web applications or simple web games that have to support older browsers).
