### ISSUE TITLE
sample app missing sample/public/socketcluster.js

### ISSUE THREAD

**Issue by tpeace** [TopCloud/socketcluster#63]
The sample app doesn't work, probably because sample/public/index.html references sample/public/socketcluster.js, which is not in this repo.  Probably because sample/public/socketcluster.js is in your .gitignore:
https://github.com/TopCloud/socketcluster/blob/a93c46e62237b7ff05e244bff8744099970edf7a/.gitignore

http://socketcluster.io/socketcluster.js exists, and I would try using it, but it looks really dated.  It still references client-side socketCluster properties that were removed in v1.3.0 (most notably 'socket.connected' and 'socket.connecting').

**Comment by tpeace** [comment]
PS: SocketCluster is a great framework.  Thanks so much for all your hard work!

**Comment by jondubois** [comment]
Did you install SC using npm?

When you install using:

```bash
npm install -g sc2
sc2 create myproject
```

^ SC will setup everything for you (it will take the socketcluster.js client and put it inside your sample app folder for you). If you setup by cloning the Git repo or if you don't install with the -g flag, then you will have to get the client and server separately and the sample app won't work by default - You will have to get the client from https://www.npmjs.com/package/sc2-client and put it inside the sample/public/ directory.

I didn't want to put the client script inside the server/sample/ directory because it's annoying to have to update whenever the client changes.
