### ISSUE TITLE
from store to worker to client

### ISSUE THREAD

**Issue by mlmarius** [TopCloud/socketcluster#67]
Hi. I made a rabbitMQ connection in my store. Now i have a callback run with the message from rabbitMQ when rabbit has messages. Problem is i don't know how to forward the message to my connected clients now. I made a listener in my worker: scServer.on('testchan',....) and from my store i do store.publish('testchan',.....) but the worker does nothing. So question is how do i listen for store events in my worker in order to forward them to the clients ? Do i have to select a particular store to listen on or is the channel enough ?

**Comment by jondubois** [comment]
You should look at how SC-Redis does it (This file should have all the logic you need: https://github.com/TopCloud/sc-redis/blob/master/index.js). SC handles a lot of the complexity there.

When you're hooking SC to an external Message Queue, you shouldn't think about end-clients at all. You should focus purely on satisfying the needs of your workers. Your workers are responsible for your figuring out how to deliver messages to clients and your code is only responsible for delivering messages to workers which are subscribed to them.

Note that the store.on('subscribe', ...) event triggers when a worker process itself asks to subscribe to the channel on the store (this event is independent from an end-user/client subscribing to a spcific channel).

For example, lets say you have two clients; ClientA and ClientB and both of them are connected to Worker1 and lets let you have one store Store1 which manages all channels within your system.

Assume that ClientA asks Worker1 to subscribe to the channel 'foo'.
Worker1 handles this and decides that it needs to subscribe itself to 'foo' on Store1 in order to start relaying the messages from that channel back to ClientA. To do this, it creates a new subscription to 'foo' on the store - The store.on('subscribe', ...) handler is triggered.
Now ClientA will start receiving messages on 'foo' from Store1.

Then assume that ClientB also asks Worker1 to subscribe to the channel 'foo'.
Worker1 handles this and notices that it is already subscribed to 'foo' on Store1 - Therefore it doesn't need to subscribe again :) So the store.on('subscribe', ...) handler does NOT run this time.

So basically events on the store are based on the worker's needs (not the end-client's).
Same with 'unsubscribe'; the 'unsubscribe' event on the store will only trigger when the worker itself doesn't need that subscription anymore (this will only happen if ALL of its end-clients unsubscribe from that channel - Or they become disconnected).

The way the 'subscribe' and 'unsubscribe' events occur on the store is quite efficient in that a worker will only subscribe to events which they actually need - There is no wasted bandwidth/CPU.

When you add more stores, what happens gets a little bit more complex (although this shouldn't affect your Message Queue 'hook' code in any way). When you have more than one store - Each store handles a subset of all channels. So basically if you have 2 stores; one of them will handle half of all the channels in your system and the other one will handle the other half - Basically each store has no idea about what the other half of channels are (it can't even publish to such a channel - Each store can only publish to their own channel).

**Comment by mlmarius** [comment]
Thanks. So from the worker, when someone connects i will subscribe to a store and listen for events on a channel. But how do i access the store and subscribe to it from my worker? I think the logic from the sc-redis repo is for the store.

**Comment by jondubois** [comment]
You can interact with a store from the worker using the Global client object (it behaves mostly like a normal client socket except that it exists on the server: http://socketcluster.io/#!/docs/api-global). The Global client can be accessed from your SCServer object in your worker.js file (scServer.global property).

For most cases though, when you want to hook up SC to an external MQ, it's better to put that logic inside store.js - It's the most efficient place.

Are you hooking it up to RabbitMQ to scale horizontally or you just want to integrate with another system on the backend?

**Comment by mlmarius** [comment]
right now i am using rabbitMQ as a messagebus in my network and socketcluster as a consumer but if things pick up i may have multiple socketcluster instances consuming from rabbitMQ.

Unfortunately i think i still don't clearly get it :). I'll attempt to make my setup clearer. This is how my store looks like:

```javascript
var rabbitCon = require('./rabbitCon');

module.exports.run = function (store) {
  console.log('   >> Store PID:', process.pid);

  //callback when rabbit has messages for us
  var cb = function(store){
        return function(msg){
                var topic = msg.fields.routingKey;
                topic = topic.substring(topic.indexOf('.')+1);
                var msgString = msg.content.toString();
                console.log('publishing topic: '+topic+' | '+msgString);
                store.publish('testchan', msgString);
        }
  }(store);

  var rql =  new rabbitCon('amqp://robobunny:Retea.@localhost:5672','topic1', 'socketcluster.*', 'socketcluster');
  rql.connect().then(function(rabbitConnObj){
        //console.log('rabbit conn now complete');
        rabbitConnObj.setCb(cb);
  });

};
```

Now i'm wondering where in my worker.js should i hook up so that i receive the events published by this store. It's not clear to me wether i should to this inside of the scServer.on('connection',...) block or before that ? 

From what i gather i think i am supposed to do something like this maybe ?

```javascript
  /*
    In here we handle our incoming realtime connections and listen for events.
  */
  scServer.on('connection', function (socket) {


    var rabbitChan =  scServer.global.subscribe('testchan');
    
    socket.on('ping', function (data) {
      count++;
      console.log('PING', data);
      scServer.global.publish('pong', count);
    });

    var interval = setInterval(function () {
      socket.emit('rand', {
        rand: Math.floor(Math.random() * 5)
      });
    }, 1000);

    socket.on('disconnect', function () {
      clearInterval(interval);
    });
  });
```

but if i do that how will i listen for events on that chan ? how would i publish a certain event on the chan. from the store all i do is store.publish('testchan', 'message'); where will i specify the event name then ?

**Comment by jondubois** [comment]
@mlmarius First of all, don't feel bad if this seems difficult (distributed message queue integration is about as difficult as it can possibly get).

Firstly, this code:

```js
 var rabbitChan = scServer.global.subscribe('testchan');
    rabbitChan.watch(function(data){
                console.log('worker received testchan data');
    });
```

should be moved outside of the 'connection' handler block (just above it is fine) - Otherwise it will keep adding new watchers every time a new user/client connects to your server (this is probably not what you want - And if you do decide to go down that path, you need to remember to unwatch them afterwards when each client disconnect - But I would advise against this approach - It always better to just deal with the Global client independently) - Also when your second user/client will connect, your global client will already be subscribed to that channel, so there is no point subscribing to it again.

^ This issue above is probably not the root of the problem though (it should still work in theory, but you would end up getting duplicate messages after multiple clients have connected to your server).

Your store.js code is not ideal from an efficiency point of view, but at first glance it looks like it should still work (theoretically, you should be able to see messages from RabbitMQ inside your worker.js). To try to figure out why it doesn't work, try to put a ```console.log(...)``` inside your RabbitMQ callback just above ```var topic = msg.fields.routingKey;``` to make sure that the message is in fact being received from RabbitMQ - Hopefully that is the issue.

The reason why your store.js code is not ideal (efficiency-wise) is because it pretends that there is a single store process. 
If you had 5 store processes, it would create 5 RabbitMQ clients, each of which would subscribe to the same RabbitMQ channel. In reality you only need one of your stores to be subscribed to that RabbitMQ channel (not all 5 - It's wasteful since only one of your stores will be responsible for the 'testchan' channel - The other stores will ignore it). 

Try to change your store.js code to this:

```javascript
var rabbitCon = require('./rabbitCon');

module.exports.run = function (store) {
  console.log('   >> Store PID:', process.pid);

  //callback when rabbit has messages for us
  var cb = function(msg){
            var topic = msg.fields.routingKey;
            topic = topic.substring(topic.indexOf('.')+1);
            var msgString = msg.content.toString();
            console.log('publishing topic: '+topic+' | '+msgString);
            store.publish('testchan', msgString);
    }

store.on('subscribe', function (channel) {
// This if block will only run on the store which is responsible for the 'testchan' channel.
if (channel == 'testchan') {
  var rql =  new rabbitCon('amqp://bunnyuser:bunnypass@localhost:5672','topic1', 'socketcluster.*', 'socketcluster');
  rql.connect().then(function(rabbitConnObj){
        //console.log('rabbit conn now complete');
        rabbitConnObj.setCb(cb);
  });
}
});
};
```

**Comment by mlmarius** [comment]
great post. Thanks!
