### ISSUE TITLE
socketPath is null in scworker

### ISSUE THREAD

**Issue by mnami** [TopCloud/socketcluster#70]
hi,
i need to access getSocketURL() value, but every time this function returns null.
_socketServer.getPath() retrun null too.

**Comment by jondubois** [comment]
@mnami Nice find. Fixed.
It happened when you used the default socket path/URL '/socketcluster/'.
Note that I took the opportunity to rename the method to worker.getSocketPath() instead of getSocketURL() - URL kind of implies that it's a full URL, but in fact it's just a relative path.

getSocketURL() still works but it has been deprecated and will be removed at some point in the future.
